cannelloni: convert to bbappend and make it conditional
cannelloni_git.bb was added to meta-agl-demo in 2020. And meta-networking
later added cannelloni_1.0.0.bb in 2021. Comparing the 2, it seems they are
mostly identical, but point to different SRCREVs, resulting in the following
error from yocto-check-layer:

INFO: test_signatures (common.CommonCheckLayer)
INFO:  ... FAIL
AssertionError: Adding layer meta-agl-demo changed signatures, basehash changed

Convert the recipe to bbappend and adjust SRCREV and PV conditionaly based on
"agldemo" AGL_FEATURES flag.

Bug-AGL: SPEC-4685
Change-Id: Ic7e53c9093d0936599f6205ef95a3a824c721bcc
Signed-off-by: Denys Dmytriyenko <denys@konsulko.com>